name: Auto Format Python Code with Black

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Black
        uses: datadog/action-py-black-formatter@v2

      - name: Commit changes
        id: commit_changes
        uses: peter-evans/create-pull-request@v7
