name: Auto Format Python Code with Black

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run Black
        run: |
          black .

      - name: Commit changes
        id: commit_changes
        uses: stefanzweifel/git-auto-commit-action@v5

      - name: "Run if changes have been detected"
        if: steps.commit_changes.outputs.changes_detected == 'true'
        run: echo "Code formated."
    
      - name: "Run if no changes have been detected"
        if: steps.commit_changes.outputs.changes_detected == 'false'
        run: echo "No Changes."
