name: Auto Format Config files & Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Run Black
        uses: actionsx/prettier@v2
        with:
          # prettier CLI arguments.
          args: --write "**/*.yml" "**/*.md"

      - name: Commit changes
        id: commit_changes
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: format & update for python
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          delete-branch: true
