name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Build the package
        run: |
          python setup.py bdist_wheel

      - name: Upload the package
        uses: actions/upload-artifact@v2
        with:
          name: python-package
          path: dist/*.whl
